### ISSUE TITLE
Docker run failed with exit code 126

### ISSUE THREAD

**Issue by JohannesKlauss** [aquariuslt/github-actions-yarn#1]
I am trying out actions to understand them and am using your action to just prettier my files.
When I try to use your action the docker run fails with exist code 126:

```
/usr/bin/docker run --name bb81f4862b713e994aad91dc63845a683356_bb1583 --label 04bb81 --workdir /github/workspace --rm -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/about-you-mobile-web-6.0/about-you-mobile-web-6.0":"/github/workspace" 04bb81:f4862b713e994aad91dc63845a683356
/usr/bin/docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/entrypoint.sh\": permission denied": unknown.
##[error]Docker run failed with exit code 126
```

This is my workflow file:

```yml
name: Prettier

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: node-10-browsers
      uses: aquariuslt/node-browsers-github-actions@v1.0.0
    - name: Install and prettier
      run: |
        yarn run install
        yarn run prettier --write src/**/*.{ts,tsx}
```

Is there something wrong with my configuration?

**Comment by aquariuslt** [comment]
@JohannesKlauss noted, I will try to re-produce in my repo.
This repo was created with github actions (deprecated HCL syntax workflow), and If I can reproduce this issue, I will update it into latest version Github Actions

**Comment by aquariuslt** [comment]
@JohannesKlauss 

I have reproduce this issue and find out a workaround, you can refer to below actions link and see it's github workflow actions

https://github.com/starter-tookits/node-chrome-app-sample/commit/08a1ab1a4af37d223c78cce90ed431d1f2dd793a/checks

below are sample repo correct workflow configurations, and two points suppose to update with your configurations (if you still want to use this actions)

1. switch actions version from `aquariuslt/node-browsers-github-actions@v1.0.0` to `aquariuslt/node-browsers-github-actions`, so that will use repo's master branch latest Dockerfile (which I add x permissions to entrypoint.sh)

2. you should add a `SCM` step to checkout your code from repository

3. running `yarn install` or `yarn` instead of `yarn run install` ☺️

```yaml
name: lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: SCM
        uses: actions/checkout@v1
      - name: node-10-browsers
        uses: aquariuslt/node-browsers-github-actions@master
      - name: Install and prettier
        run: |
          yarn install
          yarn run prettier --write src/**/*.js

```

**Comment by JohannesKlauss** [comment]
Works like a charm, thank you very much!

> 3\. running `yarn install` or `yarn` instead of `yarn run install` ☺️

Haha, true. My bad.
